TARGET = systemCmd

SRC = systemCmd.cpp

CXXFLAGS += -std=c++11 -pthread

#OBJS = $(patsubst %.cpp,%.o,$(SRC))
#COBJS = $(patsubst %.c,%.o,$(CSRC))
	
$(TARGET) : $(SRC)

#all :$(TARGET)

#.PHONY: clean
clean:
	rm -rf $(TARGET)

